#!/usr/bin/perl

# Copyright (C) 2016 Lars Hansen <lh@soem.dk>
# 
# Author: Lars Hansen <lh@soem.dk>
# 
# License:
# 
#   This package is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   This package is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#   
#   The GNU General Public License may be found at <http://www.gnu.org/licenses/>.
# 
# On Debian systems, the complete text of the GNU General
# Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

use strict;
use warnings;
use Mojo::IOLoop;
use Mojo::Log;
use FindBin;
use lib "$FindBin::Bin";
use BowlingScore;

die("Usage: $0 [info|warn|error]\n") unless !@ARGV || @ARGV == 1 && $ARGV[0] =~ /^(info|warn|error)$/;
my $log = Mojo::Log->new(level => $ARGV[0] // 'info');

BowlingScore->new(
   url => 'http://37.139.2.74/api/points',
   msg => sub {
      my ($level, @text) = @_;
      return if $level eq 'group';
      $level = 'info' unless $level =~ /^(info|warn|error|fatal)$/;
      $log->$level(@text);
   }
)->running(1);
Mojo::IOLoop->start;
