#!/usr/bin/perl

# Copyright (C) 2016-2017 Lars Hansen <lh@soem.dk>
# 
# Author: Lars Hansen <lh@soem.dk>
# 
# License:
# 
#   This package is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   This package is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#   
#   The GNU General Public License may be found at <http://www.gnu.org/licenses/>.
# 
# On Debian systems, the complete text of the GNU General
# Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

use strict;
use warnings;
use feature 'say';
use Mojo::UserAgent;

my $url = 'http://95.85.62.55/api/points';
my $ua  = Mojo::UserAgent->new;

die("Usage: $0 TOKEN SCORELIST\n") unless @ARGV == 2;
my ($token, $scorelist) = @ARGV;

my $tx = $ua->post($url, form => {token  => $token, points => $scorelist});
die(sprintf("Woops, post failed with %i\n", $tx->res->code)) unless $tx->res->code == 200;
say 'Posted data was ', $tx->res->json->{success} ? 'accepted' : 'not accepted';
