#!/usr/bin/perl

# Copyright (C) 2016 Lars Hansen <lh@soem.dk>
# 
# Author: Lars Hansen <lh@soem.dk>
# 
# License:
# 
#   This package is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   This package is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#   
#   The GNU General Public License may be found at <http://www.gnu.org/licenses/>.
# 
# On Debian systems, the complete text of the GNU General
# Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

use strict;
use warnings;
use feature 'say';
use Mojo::JSON qw(decode_json encode_json);
use FindBin;
use lib "$FindBin::Bin";
use ScoreList;

sub list_text {
   my ($label, $list) = @_;
   return sprintf('%s: %s (length %i)', $label, encode_json($list), scalar(@$list));
}

die("Usage: $0 FRAMELIST ...\n") unless @ARGV;
for my $arg (@ARGV) {
   my $frames = decode_json($arg);
   my $sl = ScoreList->new(frames => $frames);
   say list_text('Input           ', $frames);
   say list_text('Input normalized', $sl->frames);
   say list_text('Frame scores', $sl->frame_scores);
   say list_text('Scores', $sl->scores);
}
